package job.recruitment.system.seii.group.pkg6;

import java.sql.SQLException;
import java.sql.Timestamp;
import java.text.ParseException;
import java.util.logging.Level;
import java.util.logging.Logger;
import job.recruitment.system.seii.group.pkg6.FunctionalityClasses.Vacancy;
import job.recruitment.system.seii.group.pkg6.Utils.TextUtils;
import job.recruitment.system.seii.group.pkg6.Utils.VacancyTableDatabasUtils;

/**
 *
 * @author Omar
 */
    //important
    // important  
    // Please run the class ViewAllVacanciesByCertainEmployer first and you will be able to open this JForm frome their
public class ModifySelectedVacancyJFrame extends javax.swing.JFrame {
    // The vacancy that we will update
    private static Vacancy vacancy;

    public ModifySelectedVacancyJFrame(Vacancy vacancy) {
        initComponents();
        if(vacancy != null){
            this.vacancy = vacancy;
            // Set the old data to the fields to enable the user to see them
            vacancyTitleTextField.setText(vacancy.getVacancyTitle());
            vacancyDeadlineTextField.setText(new Timestamp(vacancy.getDeadlineTimeStamp()).toString());
            vacancyJobRequirmentsTextField.setText(vacancy.getVacancyJobRequirments());
        }
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        contentJPanel = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        vacancyTitleTextField = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        vacancyDeadlineTextField = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        vacancyJobRequirmentsTextField = new javax.swing.JTextField();
        saveButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("sansserif", 1, 24)); // NOI18N
        jLabel1.setText("Modify vacancy");

        jLabel3.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        jLabel3.setText("Vacancy title");

        vacancyTitleTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                vacancyTitleTextFieldActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        jLabel4.setText("Vacancy deadline");

        vacancyDeadlineTextField.setText(" yyyy-MM-dd HH:mm:ss");
        vacancyDeadlineTextField.setToolTipText("");
        vacancyDeadlineTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                vacancyDeadlineTextFieldActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        jLabel5.setText("Vacancy job requirments");

        javax.swing.GroupLayout contentJPanelLayout = new javax.swing.GroupLayout(contentJPanel);
        contentJPanel.setLayout(contentJPanelLayout);
        contentJPanelLayout.setHorizontalGroup(
            contentJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(contentJPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(contentJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(contentJPanelLayout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addGap(68, 68, 68)
                        .addComponent(vacancyJobRequirmentsTextField))
                    .addGroup(contentJPanelLayout.createSequentialGroup()
                        .addGroup(contentJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(72, 72, 72)
                        .addGroup(contentJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(vacancyTitleTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 365, Short.MAX_VALUE)
                            .addComponent(vacancyDeadlineTextField))))
                .addContainerGap())
        );
        contentJPanelLayout.setVerticalGroup(
            contentJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(contentJPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(contentJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(vacancyTitleTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(contentJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(vacancyDeadlineTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(contentJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(contentJPanelLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(contentJPanelLayout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(vacancyJobRequirmentsTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        saveButton.setText("Save");
        saveButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(contentJPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(245, 245, 245)
                        .addComponent(saveButton, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(contentJPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(saveButton, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(19, 19, 19))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void vacancyTitleTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_vacancyTitleTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_vacancyTitleTextFieldActionPerformed

    private void vacancyDeadlineTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_vacancyDeadlineTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_vacancyDeadlineTextFieldActionPerformed

    private void saveButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveButtonActionPerformed
       // Check the validity of the data
       if (!TextUtils.isEmpty(vacancyTitleTextField.getText()) && !TextUtils.isEmpty(vacancyJobRequirmentsTextField.getText()) && !TextUtils.isEmpty(vacancyDeadlineTextField.getText())){
           try {
               // Transform the date string into a unix timestamp
               long timestamp = TextUtils.transformDateIntoALongTimestamp(vacancyDeadlineTextField.getText());
               // update the values inside vacancy object.
               vacancy.setVacancyTitle(vacancyTitleTextField.getText());
               vacancy.setVacancyJobRequirments(vacancyJobRequirmentsTextField.getText());
               vacancy.setDeadlineTimeStamp(timestamp);
               VacancyTableDatabasUtils.modifyAVacancy(vacancy);
              
           } catch (ParseException ex) {
               ex.printStackTrace();
           } catch (SQLException ex) {
               ex.printStackTrace();
           }
    }
    }//GEN-LAST:event_saveButtonActionPerformed
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ModifySelectedVacancyJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ModifySelectedVacancyJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ModifySelectedVacancyJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ModifySelectedVacancyJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ModifySelectedVacancyJFrame(vacancy).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel contentJPanel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JButton saveButton;
    private javax.swing.JTextField vacancyDeadlineTextField;
    private javax.swing.JTextField vacancyJobRequirmentsTextField;
    private javax.swing.JTextField vacancyTitleTextField;
    // End of variables declaration//GEN-END:variables
}
